/*
 * This source file was generated by the Gradle 'init' task
 */


public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public String getHeader() {
        return " A O C ";
    }

    public static void main(String[] args) {
        System.out.println(new App().getHeader());
        System.out.println(new App().getGreeting());
    }
}
