/*
 * This source file was generated by the Gradle 'init' task
 */


public class App {
    public static void main(String[] args) {
        System.out.println("Advent of Code 2024\n");

        DayOne dayOne = new DayOne();
        System.out.println(dayOne.getResultA());
        System.out.println(dayOne.getResultB());

        DayOne dayTwo = new DayOne();
        System.out.println(dayTwo.getResultA());
        System.out.println(dayTwo.getResultB());
    }
}
